---
- hosts: web
#  gather_facts: False
  tasks:
    - name: ping pong
      ping:
    - name: shell
      shell: /usr/bin/cat /etc/passwd
      register: myOut
    - name: print myOut Variable
      debug: var=myOut
    - name: Install apache
      yum: name=httpd state=latest
    - name: Start service
      service: name=httpd state=started 
    - name: display the date of remote
      debug: msg={{ ansible_date_time[date] }}
    - name: Despliy Ip address from facts
      debug: msg={{ ansible_all_ipv4_addresses }}
...   
